name: MY FIRST LINUX ACTION

on: push

jobs:
  the_second_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create a New File
        run: echo "this is automation" > newfile.txt

      - name: List Files in Directory
        run: ls

      - name: Count Regular Files
        run: find . -type f | wc -l

      - name: Read and Display README.md (if exists)
        run: |
          if [ -f README.md ]; then
            cat README.md | sort
          else
            echo "README.md does not exist in the repository."
          fi